# Generated by Django 3.2 on 2022-10-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsKinds',
            fields=[
                ('goods_kinds_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_kings_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GoodSku',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_rest', models.IntegerField()),
                ('goods_statue', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GoodSpu',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=32)),
                ('type_details', models.CharField(max_length=32)),
                ('type_kinds_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodskinds')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_url', models.CharField(max_length=32)),
                ('discount_count', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=32)),
                ('img_path', models.CharField(max_length=32)),
                ('img_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodspu')),
            ],
        ),
        migrations.AddField(
            model_name='goodspu',
            name='type_shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.shift'),
        ),
    ]
