# Generated by Django 3.2 on 2022-10-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0002_orderinfo_order_stu_id'),
        ('app_goods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsku',
            name='goods_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shopping.orderinfo'),
        ),
        migrations.AlterField(
            model_name='goodsku',
            name='goods_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodspu'),
        ),
        migrations.AlterField(
            model_name='goodspu',
            name='type_kinds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodskinds'),
        ),
        migrations.AlterField(
            model_name='goodspu',
            name='type_shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.shift'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='img_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodspu'),
        ),
    ]
