# Generated by Django 3.2 on 2022-10-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0004_alter_orderinfo_order_paytype'),
        ('app_goods', '0003_auto_20221010_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsku',
            name='goods_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shopping.orderinfo'),
        ),
        migrations.AlterField(
            model_name='goodsku',
            name='goods_statue',
            field=models.IntegerField(choices=[(1, '在售'), (2, '下架')]),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='img_path',
            field=models.CharField(max_length=128),
        ),
    ]
