# Generated by Django 3.2 on 2022-10-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_auto_20221015_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspu',
            name='type_kinds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='app_goods.goodskinds'),
        ),
    ]
