# Generated by Django 3.2 on 2022-10-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_alter_goodspu_type_kinds_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspu',
            name='type_kinds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodskinds'),
        ),
    ]
