# Generated by Django 3.2 on 2022-10-15 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_addr_addr_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='addr_stu_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
