# Generated by Django 3.2 on 2022-11-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_addr_addr_stu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addr',
            name='addr_stu_id',
        ),
        migrations.AddField(
            model_name='addr',
            name='addr_stu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
