# Generated by Django 3.2 on 2022-10-10 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shopping', '0002_orderinfo_order_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_evaluate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_order.orderevaluate'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_stu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
