# Generated by Django 3.2 on 2022-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0003_auto_20221010_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_paytype',
            field=models.IntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '银行卡')]),
        ),
    ]
