# Generated by Django 3.2 on 2022-10-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shopping', '0004_alter_orderinfo_order_paytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_spu_name', models.CharField(max_length=32)),
                ('shop_sku_name', models.CharField(max_length=32)),
                ('shop_price', models.CharField(max_length=32)),
                ('stu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
