# Generated by Django 3.2 on 2022-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0005_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='shop_num',
            field=models.CharField(default=50, max_length=32),
        ),
    ]
