# Generated by Django 3.2 on 2022-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0006_shopping_shop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='shop_num',
            field=models.IntegerField(default=1),
        ),
    ]
