# Generated by Django 3.2 on 2022-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0007_alter_shopping_shop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='shop_price',
            field=models.FloatField(max_length=32),
        ),
    ]
