# Generated by Django 3.2 on 2022-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopping', '0008_alter_shopping_shop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='shop_delete',
            field=models.BooleanField(default=1),
        ),
    ]
